config/routes.rb
Rails.application.routes.draw do
  
  get 'event_registrations/success'

  resources :event_registrations
  devise_for :users
  resources :events
  resources :invites
  resources :colleges
  resources :fests
  resources :departments
  

  root 'event_registrations#new'

end

app/models/invite.rb
class Invite < ActiveRecord::Base

	has_many :college_department_invites
	has_many :college_departments, through: :college_department_invites

	validates_presence_of :title, :body

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.all
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end

  # GET /invites/new
  def new
    @invite = Invite.new
  end

  # GET /invites/1/edit
  def edit
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(invite_params)
    respond_to do |format|
      if @invite.save
        # binding.pry
        # sending email
        @invite.college_departments.each do |college_department|
          InviteMailer.send_invite(college_department, @invite.title).deliver
        end

        format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
        format.json { render :show, status: :created, location: @invite }
      else
        format.html { render :new }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { render :edit }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to invites_url, notice: 'Invite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:title, :body, college_department_ids: [])
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <div class="ui input"><%= f.text_field :title %></div><br/><br/>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %><br/><br/>
  </div>

  <div class="field">
    <%= f.collection_select :college_department_ids, CollegeDepartment.all, :id, :college_name_with_department, {prompt: "Select Colleges"}, {class: "ui fluid search dropdown", multiple: ""} %><br/>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "ui primary button" %><br/><br/>
  </div>
<% end %>

app/views/invites/edit.html.erb
<h1>Editing Invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite, class: "ui button" %>
<%= link_to 'Back', invites_path, class: "ui black button" %>

app/views/invites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invites</h1>

<%= link_to 'New Invite', new_invite_path, class: "ui primary button" %><br/><br/>

<table class="ui celled padded table dataTable">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Invitees</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @invites.each do |invite| %>
      <tr>
        <td><%= invite.title %></td>
        <td><%= invite.body %></td>
        <td>
          <% invite.college_department_invites.each do |cdi| %>
            <%= cdi.college_department.college.name %> - <%= cdi.college_department.department.name %>, 
          <% end %>    
        </td>
        <td><%= link_to 'Show', invite %></td>
        <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
        <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/invites/new.html.erb
<h1>New Invite</h1>

<%= render 'form' %>

<%= link_to 'Back', invites_path, class: "ui black button" %>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @invite.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @invite.body %>
</p>

<p>
	<strong>Invites:</strong><br/>
	<% @invite.college_department_invites.each do |cdi| %>
		<%= cdi.college_department.college.name %>
		<%= cdi.college_department.department.name %><br/>
	<% end %>
</p>

<%= link_to 'Edit', edit_invite_path(@invite), class: "ui primary button" %>
<%= link_to 'Back', invites_path, class: "ui black button" %>