config/routes.rb
Rails.application.routes.draw do
  
  get 'event_registrations/success'

  resources :event_registrations
  devise_for :users
  resources :events
  resources :invites
  resources :colleges
  resources :fests
  resources :departments
  

  root 'event_registrations#new'

end

app/models/fest.rb
class Fest < ActiveRecord::Base

	belongs_to :department
	has_many :events

	validates_presence_of :name, :description, :department_id

end

app/controllers/fests_controller.rb
class FestsController < ApplicationController
  before_action :set_fest, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /fests
  # GET /fests.json
  def index
    @fests = Fest.all
  end

  # GET /fests/1
  # GET /fests/1.json
  def show
  end

  # GET /fests/new
  def new
    @fest = Fest.new
  end

  # GET /fests/1/edit
  def edit
  end

  # POST /fests
  # POST /fests.json
  def create
    @fest = Fest.new(fest_params)

    respond_to do |format|
      if @fest.save
        format.html { redirect_to @fest, notice: 'Fest was successfully created.' }
        format.json { render :show, status: :created, location: @fest }
      else
        format.html { render :new }
        format.json { render json: @fest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fests/1
  # PATCH/PUT /fests/1.json
  def update
    respond_to do |format|
      if @fest.update(fest_params)
        format.html { redirect_to @fest, notice: 'Fest was successfully updated.' }
        format.json { render :show, status: :ok, location: @fest }
      else
        format.html { render :edit }
        format.json { render json: @fest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fests/1
  # DELETE /fests/1.json
  def destroy
    @fest.destroy
    respond_to do |format|
      format.html { redirect_to fests_url, notice: 'Fest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fest
      @fest = Fest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fest_params
      params.require(:fest).permit(:name, :description, :department_id)
    end
end

app/helpers/fests_helper.rb
module FestsHelper
end

app/views/fests/_form.html.erb
<%= form_for(@fest) do |f| %>
  <% if @fest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fest.errors.count, "error") %> prohibited this fest from being saved:</h2>

      <ul>
      <% @fest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <div class="ui input"><%= f.text_field :name %></div><br/><br/>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <div class="ui input"><%= f.text_area :description %></div><br/><br/>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.collection_select :department_id, Department.all, :id, :name, {prompt: "Select Department"}, {class: "ui search dropdown"} %><br/><br/>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "ui primary button" %><br/><br/>
  </div>
<% end %>

app/views/fests/edit.html.erb
<h1>Editing Fest</h1>

<%= render 'form' %>

<%= link_to 'Show', @fest, class: "ui button" %>
<%= link_to 'Back', fests_path, class: "ui black button" %>

app/views/fests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fests</h1>

<%= link_to 'New Fest', new_fest_path, class: "ui primary button" %><br/><br/>

<table class="ui celled padded table dataTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Department</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @fests.each do |fest| %>
      <tr>
        <td><%= fest.name %></td>
        <td><%= fest.description %></td>
        <td><%= fest.department.name %></td>
        <td><%= link_to 'Show', fest %></td>
        <td><%= link_to 'Edit', edit_fest_path(fest) %></td>
        <td><%= link_to 'Destroy', fest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/fests/new.html.erb
<h1>New Fest</h1>

<%= render 'form' %>

<%= link_to 'Back', fests_path, class: "ui black button" %>

app/views/fests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fest.description %>
</p>

<p>
  <strong>Department:</strong>
  <%= @fest.department.name %>
</p>

<strong>Events:</strong><br/>
<% @fest.events.each do |event| %>
	<b><%= event.name %></b>
	<%= "-" + event.description %><br/><br/>
<% end %>
<br/>

<%= link_to 'Edit', edit_fest_path(@fest), class: "ui primary button" %>
<%= link_to 'Back', fests_path, class: "ui black button" %>