config/routes.rb
Rails.application.routes.draw do
  
  get 'event_registrations/success'

  resources :event_registrations
  devise_for :users
  resources :events
  resources :invites
  resources :colleges
  resources :fests
  resources :departments
  

  root 'event_registrations#new'

end

app/models/college.rb
class College < ActiveRecord::Base

	has_many :college_departments
	has_many :departments, through: :college_departments
	accepts_nested_attributes_for :college_departments, allow_destroy: true

	validates_presence_of :name, :email

end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
    @college_department = CollegeDepartment.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :email, college_departments_attributes: [:id, :college_id, :department_id, :email, :_destroy])
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= nested_form_for(@college) do |f| %>
  <% if @college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% @college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <div class="ui input"><%= f.text_field :name %></div><br/><br/>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <div class="ui input"><%= f.text_field :email %></div><br/><br/><br/>
  </div>

  <%= f.fields_for :college_departments, @college_department do |cd| %>
    
    <label>Select Department: </label><br/>
    <%= cd.collection_select :department_id, Department.all, :id, :name, {prompt: "Select Department"}, {class: "ui search dropdown"} %><br/><br/>

    <label>Email: </label><br/>
    <div class="ui input"><%= cd.text_field :email %></div><br/><br/>

    <%= cd.link_to_remove "Remove Department" %><br/><br/>
  
  <% end %>

  <%= f.link_to_add "Add Department", :college_departments %><br/><br/><br/>

  <div class="actions">
    <%= f.submit "Submit", class: "ui primary button" %><br/><br/>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form' %>

<%= link_to 'Show', @college, class: "ui button" %>
<%= link_to 'Back', colleges_path, class: "ui black button" %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colleges</h1>

<%= link_to 'New College', new_college_path, class: "ui primary button" %><br/><br/>

<table class="ui celled padded table dataTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.email %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form' %>

<%= link_to 'Back', colleges_path, class: "ui black button" %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @college.email %>
</p>

<p>

	<strong>Departments:</strong><br/>
	
	<% @college.college_departments.each do |college_department| %>
		<br/><strong>Name: </strong>
		<%= college_department.department.name %><br/>
		<strong>Email: </strong>
		<%= college_department.email %><br/>
	<% end %>

</p>

<%= link_to 'Edit', edit_college_path(@college), class: "ui primary button" %>
<%= link_to 'Back', colleges_path, class: "ui black button" %>